// Package consts provides constant values for AspectGo.
package consts

// AspectGoPackagePath is the path for AspectGo.
const AspectGoPackagePath = "golang.org/x/exp/aspectgo"

// AutogenFileHeader is the header for auto-generated files.
const AutogenFileHeader = `// Automatically generated by AspectGo (` + AspectGoPackagePath + `)
// DO NOT EDIT MANUALLY

`
